apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: t3-cloneathon
data:
  POSTGRES_DB: "cloneathon_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PORT: "5432"
  REDIS_PORT: "6379"
  NODE_ENV: "production"
registries:
  - name: GitHub Container Registry
    api_url: https://ghcr.io
    prefix: ghcr.io
    ping: yes
    credentials: secret:argocd/ghcr-secret#token
