apiVersion: v1
kind: Secret
metadata:
  name: ghcr-io-secret
  namespace: t3-cloneathon
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAidXNlcm5hbWUiOiAiUkVQTEFDRV9XSVRIX1lPVVJfR0lUSFVCX1VTRVJOQU1FIiwKICAgICAgInBhc3N3b3JkIjogIlJFUExBQ0VfV0lUSF9ZT1VSX0dJVEhVQl9UT0tFTiIsCiAgICAgICJhdXRoIjogIlJFUExBQ0VfV0lUSF9CQVNFNjRfQ1JFREVOVElBTFMiCiAgICB9CiAgfQp9
---
# To create this secret properly, run:
# kubectl create secret docker-registry ghcr-io-secret \
#   --docker-server=ghcr.io \
#   --docker-username=YOUR_GITHUB_USERNAME \
#   --docker-password=YOUR_GITHUB_TOKEN \
#   --namespace=t3-cloneathon
