apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: t3-cloneathon
  annotations:
    description: "Application secrets - all values must be base64 encoded"
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=  # postgres_password
  REDIS_PASSWORD: "XghylgG+3Khvfn0WtjvHNNJDopFIgx6DeHvuMLGZzDc="  # Add your Redis password base64 encoded (empty if no password)
  BETTER_AUTH_SECRET: "bcPnMw4l7Q/+MQobsqtHOyk+MsSbPcwJ9X2GGwFGm94="  # your_better_auth_secret_key
  DISCORD_CLIENT_ID: "bcPnMw4l7Q/+MQobsqtHOyk+MsSbPcwJ9X2GGwFGm94="
  DISCORD_CLIENT_SECRET: "KnGFuhiTbVZjZCGYg5BGKx5OgC7plq108QXdgKj8Wzg="